# ==========================
# CONFIG
# ==========================
NAME        = test_parser

CXX         = c++
CXXFLAGS    = -Wall -Wextra -Werror -std=c++98

INCLUDES    = -I src/includes

HTTP_DIR    = src/http

SRCS        = \
	$(HTTP_DIR)/test_parser.cpp \
	$(HTTP_DIR)/HttpRequestParser.cpp \
	$(HTTP_DIR)/HttpResponse.cpp

OBJS        = $(SRCS:.cpp=.o)

# ==========================
# RULES
# ==========================

all: $(NAME)

$(NAME): $(OBJS)
	$(CXX) $(CXXFLAGS) $(OBJS) -o $(NAME)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) $(INCLUDES) -c $< -o $@

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all

# ==========================
# PHONY
# ==========================

.PHONY: all clean fclean re
